config:
  bind: 0.0.0.0:${GATE_BIND_PORT}
  onlineMode: true
  forwarding:
    mode: velocity
    velocitySecret: ${VELOCITY_FORWARDING_SECRET}
  servers:
    ${WAITING_SERVER_NAME}: ${WAITING_SERVER_ADDRESS}
    ${MC_SERVER_NAME}: ${MC_SERVER_ADDRESS}
  try:
    - ${WAITING_SERVER_NAME}
  query:
    enabled: false
  lite:
    enabled: false
